version: "3.7"

services:

  ui:
    image: registry.dev.n18.an.cnav/phishing/phishing-ui:${VERSION:-latest}
    networks:
      - front-network
    deploy:
      labels:
        - "traefik.docker.network=front-network"
        - "traefik.http.routers.phishing-${NEWCOLOR:-blue}.priority=10"
        - "traefik.http.routers.phishing-${NEWCOLOR:-blue}.rule=HostRegexp(`phishing.{domain:[a-z0-9\\.]+}`)"
        # - "traefik.http.routers.phishing-${NEWCOLOR:-blue}.rule=Host(`slt03092.dev.n18.an.cnav`)"
        - "traefik.http.services.phishing-${NEWCOLOR:-blue}.loadbalancer.server.port=80"

networks:

  front-network:
    external: true
    